annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Upgrading SonarQube to 10.1.0"
    - kind: changed
      description: "Support Kubernetes v1.27 while dropping v1.23"
    - kind: changed
      description: "Changed default test process to wget, using sonarqube image as default"
    - kind: changed
      description: "Fix wrong condition between initFs and concat-properties"
    - kind: changed
      description: "Update Chart's version to 10.1.0"
    - kind: changed
      description: "Fix liveness probe for SonarQube Application to detect when a failure occurs."
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: sonarqube-app
      image: sonarqube:10.1.0-datacenter-app
    - name: sonarqube-search
      image: sonarqube:10.1.0-datacenter-search
  artifacthub.io/links: |
    - name: support
      url: https://community.sonarsource.com/
    - name: Chart Source
      url: https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube-dce
apiVersion: v2
appVersion: 10.1.0
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
  version: 10.15.0
- condition: nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.0.13
description: SonarQube is a self-managed, automatic code review tool that systematically
  helps you deliver clean code. As a core element of our Sonar solution, SonarQube
  integrates into your existing workflow and detects issues in your code to help you
  perform continuous code inspections of your projects. The tool analyses 30+ different
  programming languages and integrates into your CI pipeline and DevOps platform to
  ensure that your code meets high-quality standards.
home: https://www.sonarqube.org/
icon: https://raw.githubusercontent.com/SonarSource/sonarqube-static-resources/master/helm/SonarQubeLogo.svg
keywords:
- coverage
- security
- code
- quality
kubeVersion: '>= 1.19.0-0'
maintainers:
- email: leo.geoffroy+helm@sonarsource.com
  name: leo-geoffroy-sonarsource
- email: carmine.vassallo@sonarsource.com
  name: carminevassallo
- email: jeremy.cotineau@sonarsource.com
  name: jCOTINEAU
name: sonarqube-dce
sources:
- https://github.com/SonarSource/helm-chart-sonarqube
- https://github.com/SonarSource/docker-sonarqube
- https://github.com/SonarSource/sonarqube
type: application
version: 10.1.0+628
