name: Deploy Sonarqube with helm

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run in dry_run mode e.g --dry-run"
        required: true
        type: boolean
        default: false

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
  repo: "https://SonarSource.github.io/helm-chart-sonarqube"
  namespace: "sonarqube-dce"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'
      
      - name: Set up helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.11.0'

  #validate:
  #  runs-on: ubuntu-latest
  #  needs: setup
  #  steps:
      - name: Validate kubectl and helm installation
        run: |
          helm version
          kubectl version
          kubectl get no
  
  deploy:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Add Sonar repo
        run: |
          helm repo add sonarqube ${{ env.repo }}
          helm repo update

      - name: Run in dry-run mode
        if: ${{ github.event.inputs.dry_run }}
        run: |
          echo "Run the sonarqube helm chart in dry_run mode" 
          helm upgrade -i -n${{ env.namespace }} sonarqube-dce -f sonar-values.yaml sonarqube-dce/ --dry-run

      - name: Deply sonarqube
        if: ${{ github.event.inputs.dry_run == 'false' }}
        run: |
          echo "Deply sonarqube helm chart"
          helm upgrade -i -n${{ env.namespace }} sonarqube-dce -f sonar-values.yaml sonarqube-dce/

  verify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Show deployment details
        run: kubectl get all -n${{ env.namespace }}
